### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by Cactooz** [insektionen/cleaning-list-fe#7]
Currently, you need to click on your profile in order to log out, it would be handy to have a logout button directly in the navbar as well.

**Comment by Cactooz** [comment]
I'd personally prefer the suggestion version, but #5 is better than how it currently is at least if it could be a hover to show the settings or similar.

**Comment by StelFoog** [comment]
> I'd personally prefer the suggestion version, but #5 is better than how it currently is at least if it could be a hover to show the settings or similar.

Since it's primarily supposed to be used on mobile a hover wouldn't show. If it were to be in the navbar I would still like a confirm dialog before allowing the user to sign out since a misclick would be costly in time. So either way it should be a 2 click action IMO.

**Comment by Cactooz** [comment]
Fair enough, it might be easier to manage when you are not testing the site and logging in and out a lot!

**Comment by StelFoog** [comment]
Yeah, I expect sign out to not be a widely used feature for normal users in prod since intended use is mostly on mobile (one-user) devices.

The only scenario I can see where it would be frequently used is for someone switching from their regular account into an `admin` account to perform actions only available for admins. Though they are few enough that should still be rare.
